@startuml Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"

!include $ICONURL/devicons2/flutter.puml
!include $ICONURL/devicons2/chrome.puml
!include $ICONURL/font-awesome-5/laravel.puml
!include $ICONURL/devicons/mysql.puml
!include $ICONURL/devicons2/redis.puml
!include $ICONURL/devicons2/rabbitmq_original.puml
!include $ICONURL/material/web.puml

'LAYOUT_WITH_LEGEND()'

System_Boundary(frontend, "Frontend") {
    Container(mobileApp, "Mobile Application", "flutter", "Интерфейс, с которым взаимодействует пользователь", $sprite="flutter")
    Container(webApp, "Admin MPA", "html/css", "Интерфейс, с которым взаимодействует модератор", $sprite="chrome")
}

System_Boundary(backend, "Backend") {
    Container(websocket, "Websocket Server", "Ratchet", "Обрабатывает логику приложения в реальном времени", $sprite="web")

    Container(api, "REST API Application", "Laravel", "Обрабатывает основную логику приложения", $sprite="laravel")

    Container(redis, "Redis Server", "Redis", "Хранилище в оперативной памяти", $sprite="redis")

    Container(rabbitMQ, "RabbitMQ Server", "RabbitMQ", "Брокер сообщений", $sprite="rabbitmq_original")

    ContainerDb(db, "Database", "MySQL", "Хранит информацию о пользователях, достопримечательностях, маршрутах и т.д.", $sprite="mysql")
}



Rel(mobileApp, api, "Uses", "https/json, wss")
Rel(webApp, api, "Uses", "https/json, html")
Rel_D(api, db, "Reads/Writes", "CRUD")
Rel_D(api, rabbitMQ, "Uses", "DTO")
Rel_D(websocket, rabbitMQ, "Uses", "DTO")
Rel_D(api, redis, "Reads/Writes", "DTO")
Rel_D(websocket, redis, "Reads/Writes", "DTO")

@enduml